DROP DATABASE IF EXISTS epsservice;
DROP USER IF EXISTS `eps_service`@`%`;
CREATE DATABASE IF NOT EXISTS epsservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `eps_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `epsservice`.* TO `eps_service`@`%`;
FLUSH PRIVILEGES;